### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by zitaretz** [ddiem-ri-4D/epiTCR#1]
Hi there, 
I am trying to run this program for the first time. However, I am running into an issue with the test data because it didn't seem to recognize the model file. 
This is the error message I receive. 
predict.py: error: unrecognized arguments: --model_file models/rdforestWithMHCModel.pickle
I unzipped the file and downloaded all dependencies - do you have any idea what the issue could be? 

Best, Zita

**Comment by ddiem-ri-4D** [comment]
Hi Zita,

I apologize for the mistake. I have updated the README.md file. Please change "--model_file" to "--modelfile" instead. Thank you so much for your help.

Best regards,
Mỹ Diễm.

<img width="925" alt="Screenshot 2023-05-08 at 10 32 59 PM" src="https://user-images.githubusercontent.com/50079932/236866234-05f3dcfb-42c4-4866-8008-b70bec913b3a.png">
