### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JoshuaMeyers** [ddiem-ri-4D/epiTCR#4]
Hey @ddiem-ri-4D, awesome work. What license have you released the code under? I'd love to try it out at work. Cheers, J.

**Comment by ddiem-ri-4D** [comment]
Hi @JoshuaMeyers,

I have added the license. Thank you for your interest in my repository.

Best regards,
My Diem.

**Comment by JoshuaMeyers** [comment]
Thanks a lot @ddiem-ri-4D
