### ISSUE TITLE
Question about binder in input file.

### ISSUE THREAD

**Issue by xxl619755841** [ddiem-ri-4D/epiTCR#5]
Hello
  Thanks for your great tool.
  I have a question about the input file. When I run epiTCR without MHC in prediction mode use pre-trained model. I find I must add the binder column. So is this my own assumption about the TCR and epitipe bindinig? And in the result file, should I rely on the predict_proba and binder_pred information? 
 Some simple questions and thank for your patience!!

**Comment by ddiem-ri-4D** [comment]
Hi @xxl619755841,

That's correct, the binder column is only an assumption about TCR and epitope binding (I used it for benchmarking). The data you use for prediction might not require this column. In the result file, you rely on predict_proba and binder_pred information to determine whether the TCR and epitope have binding, and what the specific predicted probability is.

Thank you for your interest.
Best regards,

My Diem.

**Comment by xxl619755841** [comment]
Oh, Thanks for your quick response!
You said my data may not require the binder column. But when I ran the tools using the test data and deleted the binder column, I got an error like below. 
(use predict.py and --chain is ce)
![image](https://github.com/ddiem-ri-4D/epiTCR/assets/34829611/f061c0bb-5a1f-4bcf-afd7-f8355218e91e)
It's just a little question and won't influence use when the data has the 'binder' column. I can add the colum by myself. Just remind you.

Thanks again for your effort for the great tool.

**Comment by ddiem-ri-4D** [comment]
Hi @xxl619755841,

Actually, **predicMLModel**(...) function already includes plotting ROC, calculating sensitivity, specificity, accuracy, and AUC, so it requires the y_test data. If you don't have data for the binder column, you can remove the code section below (the highlighted yellow code below, which is related to y_test). You can either pass None as the y_test parameter or modify the source code not to pass y_test. However, if you already have y_test, that would be better.

Thank you for your interest.

Best regards,
My Diem

![Screenshot 2023-08-24 at 16 04 45](https://github.com/ddiem-ri-4D/epiTCR/assets/50079932/d952c365-cf2c-4d48-8661-462c7e0dd32e)

**Comment by nttvy** [comment]
@ddiem-ri-4D we should update the code so that the application users don't have to change the code themselves
@xxl619755841 Thanks a lot for your comment. We will fix the code in the next version. Meanwhile, we would suggest you remove the code as above (if you are familiar with coding), or generate random values to the last column and ignore the visualization part of the output.

Bests,
Vy
