### ISSUE TITLE
Does not work for peptides longer than 11 amino acids

### ISSUE THREAD

**Issue by Leob44** [ddiem-ri-4D/epiTCR#8]
Hello, 

Everytime I try to predict binding of a peptide longer than 11 amino acids, I get the error : "could not broadcast input array from shape (25,20) into shape (11,20)". 

Any clue how I might solve that ? 

Thanks

**Comment by ddiem-ri-4D** [comment]
Hello @Leob44 ,

Are you sure your peptide has a length of 11? Looking at your error, I see that the current length is 25, so your array size is (25,12).
For my model, the input data requires a peptide length <= 11, so the fixed size is always (11,20).
Please double-check your data, and if the issue persists, feel free to send the data for me to check and assist you with the problem you're encountering.

Thank you for your attention.
Best regards,
My Diem

**Comment by ddiem-ri-4D** [comment]
Hi @Leob44,

For my model, the input data requires the peptide length to be >=8 and <=11, so the fixed size is always (11,20). Considering that your peptides have a length >=11, you need to exclude those peptides from the test set to use my model. 

Thank you for your attention.

Best regards, 
My Diem

![Screenshot 2024-03-09 at 2 24 44 PM](https://github.com/ddiem-ri-4D/epiTCR/assets/50079932/73f16c96-dee1-43f4-9eeb-157c29c2442d)
